name: CustomCobbleGen
main: me.phil14052.CustomCobbleGen.CustomCobbleGen
version: 1.1.2
author: phil14052
description: Adds the ability to change the cobblestone generator
api-version: 1.14
softdepend: [Vault, PlaceholderAPI]
commands:
  cobblegen:
    description: CustomCobbleGen Plugin Main Command
    aliases: [oregen, cobblegenerator, oregenerator]